<?php
class HomeController
{
    private Product $productModel; private Category $categoryModel; private Review $reviewModel;
    private Order $orderModel;
    public function __construct() { $this->productModel = new Product(); $this->categoryModel = new Category(); $this->reviewModel = new Review(); $this->orderModel = new Order(); }
    private function requireLogin(): void { if (empty($_SESSION['user'])) { header('Location: ' . BASE_URL . '?action=login'); exit; } }
    private function rejectAdmin(): void { if (($_SESSION['user']['role'] ?? '') === 'admin') { header('Location: ' . BASE_URL . '?action=admin-dashboard'); exit; } }
    public function index(): void { $this->requireLogin(); $this->rejectAdmin(); $title='Trang chủ'; $view='user/home'; $layout='user'; $categories=$this->categoryModel->getAll(); $featuredProducts=$this->productModel->getCatalog(['sort'=>'rating'],4); $newProducts=$this->productModel->getCatalog([],8); require PATH_VIEW_MAIN; }
    public function products(): void { $this->requireLogin(); $this->rejectAdmin(); $filters=['keyword'=>trim($_GET['keyword']??''),'danh_muc_id'=>(int)($_GET['category']??$_GET['danh_muc_id']??0),'min_price'=>$_GET['min_price']??'','max_price'=>$_GET['max_price']??'','sort'=>$_GET['sort']??'']; $title='Sản phẩm'; $view='user/products'; $layout='user'; $products=$this->productModel->getCatalog($filters); $categories=$this->categoryModel->getAll(); require PATH_VIEW_MAIN; }
    public function categories(): void { $this->requireLogin(); $this->rejectAdmin(); $title='Danh mục'; $view='user/categories'; $layout='user'; $categories=$this->categoryModel->getAll(); require PATH_VIEW_MAIN; }
    public function productDetail(): void { $this->requireLogin(); $this->rejectAdmin(); $productId=(int)($_GET['id']??0); $product=$this->productModel->findById($productId); if(!$product){http_response_code(404);$title='Không tìm thấy sản phẩm';$view='errors/404';$layout='user';require PATH_VIEW_MAIN;return;} $reviews=$this->reviewModel->getByProductId($productId);$ratingInfo=$this->reviewModel->getAverageRating($productId);$myReview=null;foreach($reviews as $review){if((int)$review['user_id']===(int)$_SESSION['user']['id']){$myReview=$review;break;}}$title=$product['name'];$view='user/product_detail';$layout='user';require PATH_VIEW_MAIN; }
    public function storeReview(): void { $this->requireLogin();$productId=(int)($_POST['san_pham_id']??0);try{if(!csrf_validate($_POST['csrf_token']??null)||!$this->orderModel->canReview((int)$_SESSION['user']['id'],$productId))throw new RuntimeException('Chỉ đánh giá sau khi đơn hoàn thành.');$old=$this->reviewModel->findByUserProduct((int)$_SESSION['user']['id'],$productId);if($old)$this->reviewModel->update($old['id'],$_SESSION['user']['id'],$_POST);else $this->reviewModel->create(['san_pham_id'=>$productId,'user_id'=>$_SESSION['user']['id'],'so_sao'=>$_POST['so_sao']??5,'noi_dung'=>$_POST['noi_dung']??'']);$_SESSION['success_message']='Đã lưu đánh giá.';}catch(Throwable $e){$_SESSION['error_message']=$e->getMessage();}header('Location: '.BASE_URL.'?action=product-detail&id='.$productId);exit; }
    public function updateReview(): void { $this->requireLogin();$productId=(int)($_POST['san_pham_id']??0);$this->reviewModel->update((int)($_POST['id']??0),(int)$_SESSION['user']['id'],$_POST);header('Location: '.BASE_URL.'?action=product-detail&id='.$productId);exit; }
    public function deleteReview(): void { $this->requireLogin();$productId=(int)($_GET['san_pham_id']??0);$this->reviewModel->delete((int)($_GET['id']??0),(int)$_SESSION['user']['id']);header('Location: '.BASE_URL.'?action=product-detail&id='.$productId);exit; }
    public function cart(): void { $this->requireLogin();$this->rejectAdmin();$warnings=[];$cartModel=new Cart();$cartItems=$cartModel->getItems($warnings);$totalQuantity=$cartModel->getTotalQuantity();$totalAmount=array_sum(array_column($cartItems,'subtotal'));$title='Giỏ hàng';$view='user/cart';$layout='user';require PATH_VIEW_MAIN; }
    public function addToCart(): void { $this->requireLogin();$productId=(int)($_POST['san_pham_id']??0);try{$result=(new Cart())->add($productId,(int)($_POST['variant_id']??0),(int)($_POST['quantity']??1));$_SESSION['success_message']='Đã thêm '.$result['product_name'].' vào giỏ hàng.';}catch(Throwable $e){$_SESSION['error_message']=$e->getMessage();}header('Location: '.BASE_URL.'?action=product-detail&id='.$productId);exit; }
    public function updateCart(): void { $this->requireLogin();try{(new Cart())->updateQuantity((int)($_POST['variant_id']??$_GET['variant_id']??0),(int)($_POST['quantity']??$_GET['quantity']??0));}catch(Throwable $e){$_SESSION['error_message']=$e->getMessage();}header('Location: '.BASE_URL.'?action=cart');exit; }
    public function removeFromCart(): void { $this->requireLogin();(new Cart())->remove((int)($_POST['variant_id']??$_GET['variant_id']??0));header('Location: '.BASE_URL.'?action=cart');exit; }
    public function clearCart(): void { $this->requireLogin();(new Cart())->clear();header('Location: '.BASE_URL.'?action=cart');exit; }
    public function checkout(): void { $this->requireLogin();$this->rejectAdmin();$warnings=[];$cartItems=(new Cart())->getItems($warnings);$totalAmount=array_sum(array_column($cartItems,'subtotal'));$user=$_SESSION['user'];$title='Thanh toán';$view='user/checkout';$layout='user';require PATH_VIEW_MAIN; }
    public function placeOrder(): void { $this->requireLogin();$this->rejectAdmin();if($_SERVER['REQUEST_METHOD']!=='POST'||!csrf_validate($_POST['csrf_token']??null)){$_SESSION['error_message']='Yêu cầu không hợp lệ.';header('Location: '.BASE_URL.'?action=checkout');exit;}$recipient=['name'=>trim($_POST['recipient_name']??''),'phone'=>trim($_POST['recipient_phone']??''),'address'=>trim($_POST['recipient_address']??''),'note'=>trim($_POST['note']??'')];if(!$recipient['name']||!$recipient['phone']||!$recipient['address']){$_SESSION['error_message']='Vui lòng nhập đủ thông tin nhận hàng.';header('Location: '.BASE_URL.'?action=checkout');exit;}try{$warnings=[];$cart=new Cart();$order=$this->orderModel->createFromCart((int)$_SESSION['user']['id'],$recipient,$cart->getItems($warnings));$cart->clear();$_SESSION['success_message']='Đặt hàng thành công.';header('Location: '.BASE_URL.'?action=order-detail&id='.$order['id']);exit;}catch(Throwable $e){$_SESSION['error_message']=$e->getMessage();header('Location: '.BASE_URL.'?action=checkout');exit;}}
    public function orders(): void { $this->requireLogin();$this->rejectAdmin();$orders=$this->orderModel->getByUser((int)$_SESSION['user']['id']);$title='Đơn hàng của tôi';$view='user/orders';$layout='user';require PATH_VIEW_MAIN; }
    public function orderDetail(): void {$this->requireLogin();$this->rejectAdmin();$order=$this->orderModel->findForUser((int)($_GET['id']??0),(int)$_SESSION['user']['id']);if(!$order){http_response_code(403);$title='Không có quyền';$view='errors/403';$layout='user';require PATH_VIEW_MAIN;return;}$title='Chi tiết đơn hàng';$view='user/order_detail';$layout='user';require PATH_VIEW_MAIN;}
    public function profile(): void { $this->requireLogin();$this->rejectAdmin();$user=$_SESSION['user'];$title='Hồ sơ';$view='user/profile';$layout='user';require PATH_VIEW_MAIN; }
}
